# local development environment
version: '3'
services:

  msmtp-build-environment:
    user: "0:0" # be root user in order to modify mounted files
    build:
      dockerfile: ./docker/debug/Dockerfile
      context: .
    image: msmtp-build-environment-debian:latest
    container_name: debian-msmtp
    entrypoint: /bin/bash
    command: -c "while true; do echo 'sleeping for another 5 seconds'; sleep 5; done"
    environment:
      # custom prefix where we want the files to finally be
      PREFIX: "/usr/local"
    volumes:
      - ".:/build"